Added random caption generator
deeqakkk/Journey-with-js pull request #43
Opened 2022-10-14 12:38 UTC by ranjeet25

### You can generate random captions and you can copy them to your clipboard by just clicking on the copy button 🔥⭐ 
Screenshots :

![image](https://user-images.githubusercontent.com/79698226/195848134-2939d2a7-9ce8-4053-9b81-39175452bbb4.png)

Mobie View 

![image](https://user-images.githubusercontent.com/79698226/195848331-27cfa66a-b529-4178-8e8f-fd3f0dca835d.png)

###  @deeqakkk you can review my PR !!

2022-10-14 15:09 UTC, deeqakkk commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
delete this file, it is not required.

2022-10-14 15:10 UTC, deeqakkk requested changes
Everything looks good, just delete a file and update the folder name.

2022-10-14 15:33 UTC, ranjeet25 commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
@deeqakkk deleted !!

2022-10-14 15:36 UTC, ranjeet25 commented
> Everything looks good, just delete a file and update the folder name.

my project number is 6 so I have made folder according to it 

> 

My project number was 6 so I have named my folder according to it. @deeqakkk  you can verify !!

2022-10-20 15:12 UTC, ranjeet25 commented
@deeqakkk  Can you Please merge my Pull request !! I have made the changes

2022-10-21 07:51 UTC, deeqakkk approved these changes

2022-10-21 07:51 UTC, merged

2022-10-21 07:52 UTC, deeqakkk commented
Good Work Ranjeet 👏🏼