Parallex Effect
deeqakkk/Journey-with-js pull request #54
Opened 2022-10-15 05:52 UTC by Saadansariii

Added my simple parallex effect wweb

2022-10-16 16:06 UTC, deeqakkk requested changes
Please create a new folder 'assests' and put all the images in that and also update your main folder name as "20-Photography-Effect"

2022-10-17 04:20 UTC, Saadansariii commented
I make all the changes as u said ....if i made any problem lemme know

2022-10-21 07:57 UTC, deeqakkk approved these changes

2022-10-21 07:57 UTC, deeqakkk commented
Good Work @Saadansariii 👏🏼

2022-10-21 07:57 UTC, merged