Apple HomePage added
deeqakkk/Journey-with-js pull request #56
Opened 2022-10-15 05:54 UTC by Saadansariii

Apple HOmepage only looks good on big screen

2022-10-16 16:01 UTC, deeqakkk commented on 18 - Apple HomePage/css/style.css
> +    outline: none;
move this file directly in the "apple homepage' folder and delete the folder "CSS".

2022-10-16 16:02 UTC, deeqakkk commented on 18 - Apple HomePage/html/index.html
> +
delete the folder "HTML" and put index file directly in "apple homepage" folder.

2022-10-16 16:03 UTC, deeqakkk requested changes
Please make the mentioned changes.

2022-10-17 04:26 UTC, Saadansariii commented
> Please make the mentioned changes.

i did't all the things as u said

2022-10-21 08:00 UTC, deeqakkk requested changes
![image](https://user-images.githubusercontent.com/78724676/197144513-64d4d5c0-db64-49bd-8447-dae46c8e6d8b.png)
![image](https://user-images.githubusercontent.com/78724676/197144562-91621552-abee-4388-b7d5-631d7e2ec397.png)
![image](https://user-images.githubusercontent.com/78724676/197144617-6a77172a-970a-4b76-963a-b8ae135bf677.png)

Please check with image src, images are not getting rendered properly.

2022-10-21 14:21 UTC, Saadansariii commented
I did my best to resolve all the issue that u raised

2022-10-22 17:08 UTC, merged

2022-10-22 17:08 UTC, deeqakkk commented
> I did my best to resolve all the issue that u raised

You did a great jon @Saadansariii .